name: Rails

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec-tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      # The hostname used to communicate with the PostgreSQL service container
      POSTGRES_HOST: postgres
      # The default PostgreSQL port
      POSTGRES_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install DB libraries
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: bundle install
      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rails db:drop db:create db:migrate
          bundle exec rails db:reset
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Run tests
        run: COVERAGE=true bundle exec rspec  --require rails_helper
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
